### PR TITLE
Fix regression from #91

### PR DESCRIPTION
**Pull request by chanchiwai-ray**
PR #91 did not add `client` argument to all function calls to `get_all_external_repos`, which causes issue like

```python
  File "/snap/openstack/x24/lib/python3.10/site-packages/sunbeam/jobs/plugin.py", line 228, in                          
enabled_plugins                                                                                                         
    repos.extend(cls.get_all_external_repos())
TypeError: PluginManager.get_all_external_repos() missing 1 required positional argument: 'client' 
````

This PR addresses the regression.

### CODE REVIEW

**Comment by hemanthnakkina** [comment]
/canonical/self-hosted-runners/run-workflows 9a4b12cbbd9aa2dfbe3b5458849f3ef5c3ecb2a7

**Review by hemanthnakkina — APPROVED** [review]
